function h(){$(".navbar-toggle").click(function(a){var b=$(this).closest("nav"),c=b.find("ul.site-navigation"),d=c.clone();c.parent().f("nav-special")&&((a.stopPropagation(),$(this).f("selected-nav"))?($(".blocsapp-special-menu blocsnav").c("open"),$(".selected-nav").c("selected-nav"),setTimeout(function(){$(".blocsapp-special-menu").remove();$("body").c("lock-scroll");$(".selected-nav").c("selected-nav")},300)):($(this).b("selected-nav"),a=b.a("class").replace("navbar","").replace("row",""),c=c.parent().a("class").replace("navbar-collapse",
"").replace("collapse",""),$(".content-tint").length=-1,$("body").append('<div class="content-tint"></div>'),d.insertBefore(".page-container").L('<div class="blocsapp-special-menu '+a+'"><blocsnav class="'+c+'">'),$("blocsnav").prepend('<a class="close-special-menu animated fadeIn" style="animation-delay:0.5s;"><div class="close-icon"></div></a>'),function(){var e="fadeInRight",f=0,g=60;$(".blocsapp-special-menu blocsnav").f("fullscreen-nav")?(e="fadeIn",g=100):$(".blocsapp-special-menu").f("nav-invert")&&
(e="fadeInLeft");$(".blocsapp-special-menu blocsnav li").i(function(){$(this).parent().f("dropdown-menu")?$(this).b("animated fadeIn"):(f+=g,$(this).a("style","animation-delay:"+f+"ms").b("animated "+e))})}(),setTimeout(function(){$(".blocsapp-special-menu blocsnav").b("open");$(".content-tint").b("on");$("body").b("lock-scroll")},10)))});$("body").j("mousedown touchstart",".content-tint, .close-special-menu",function(){$(".content-tint").c("on");$(".selected-nav").click();setTimeout(function(){$(".content-tint").remove()},
10)}).j("click",".blocsapp-special-menu a",function(a){$(a.target).closest(".dropdown-toggle").length||$(".close-special-menu").F()})}
function k(){$(".site-navigation a").click(function(a){$(a.target).closest(".dropdown-toggle").length||$(".navbar-collapse").collapse("hide")});$("a.dropdown-toggle").click(function(){$(this).parent().b("target-open-menu");$(this).closest(".dropdown-menu").find(".dropdown.open").i(function(){$(this).f("target-open-menu")||$(this).c("open")});$(".target-open-menu").c("target-open-menu")})}
function l(){$(".bloc-fill-screen").i(function(){var a=$(this);window.B=0;$(this).find(".container").i(function(){fillPadding=2*parseInt($(this).h("padding-top"));a.f("bloc-group")?fillBodyHeight=fillPadding+$(this).outerHeight()+50:fillBodyHeight=fillBodyHeight+fillPadding+$(this).outerHeight()+50});$(this).h("height",m()+"px")})}function m(){var a=$(window).height();return a<fillBodyHeight&&(a=fillBodyHeight+100),a}
function n(){p();q();$(window).scroll(function(){q();$(window).scrollTop()>$(window).height()/3?$(".scrollToTop").f("showScrollTop")||$(".scrollToTop").b("showScrollTop"):$(".scrollToTop").c("showScrollTop");var a=0,b="sticky";$(".sticky-nav").f("fill-bloc-top-edge")&&(a=$(".fill-bloc-top-edge.sticky-nav").parent().h("background-color"),"rgba(0, 0, 0, 0)"==a&&(a="#FFFFFF"),$(".sticky-nav").h("background",a),a=$(".sticky-nav").height(),b="sticky animated fadeInDown");$(window).scrollTop()>a?($(".sticky-nav").b(b),
"sticky"==b&&$(".page-container").h("padding-top",$(".sticky-nav").height())):($(".sticky-nav").c(b).m("style"),$(".page-container").m("style"))})}function r(){$("ul.dropdown-menu [data-toggle=dropdown]").j("click",function(a){a.preventDefault();a.stopPropagation();$(this).parent().G().c("open");$(this).parent().J("open");a=$(this).parent().children(".dropdown-menu");a.offset().left+a.width()>$(window).width()&&a.b("dropmenu-flow-right")})}
function p(){$(".animated").i(function(){$(this).closest(".hero").length||$(this).c("animated").b("hideMe")})}function q(){$($(".hideMe").get().reverse()).i(function(){var a=jQuery(this),b=a.offset().top+a.height(),c=$(window).scrollTop()+$(window).height();if(a.height()>$(window).height()&&(b=a.offset().top),b<c){var d=a.a("class").replace("hideMe","animated");a.h("visibility","hidden").m("class");setTimeout(function(){a.a("class",d).h("visibility","visible")},.01)}})}
function t(){$(document).j("click","[data-toggle-visibility]",function(a){function b(d){d.is("img")?d.toggle():d.H()}a.preventDefault();a=$(this).a("data-toggle-visibility");if(-1!=a.indexOf(",")){var c=a.split(",");$.i(c,function(d){b($("#"+c[d]))})}else b($("#"+a))})}
function u(){window.I;$(document).j("click","[data-lightbox]",function(a){a.preventDefault();targetLightbox=$(this);a=targetLightbox.a("data-lightbox");var b=targetLightbox.a("data-autoplay"),c='<p class="lightbox-caption">'+targetLightbox.a("data-caption")+"</p>",d="no-gallery-set",e=targetLightbox.a("data-frame");targetLightbox.a("data-gallery-id")&&(d=targetLightbox.a("data-gallery-id"));targetLightbox.a("data-caption")||(c="");var f="";1==b&&(f="autoplay");b=$('<div id="lightbox-modal" class="modal fade"><div class="modal-dialog"><div class="modal-content '+
e+' blocs-lb-container"><button id="blocs-lightbox-close-btn" type="button" class="close-lightbox" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button><div class="modal-body"><a href="#" class="prev-lightbox" aria-label="prev"><span class="fa fa-chevron-left"></span></a><a href="#" class="next-lightbox" aria-label="next"><span class="fa fa-chevron-right"></span></a><img id="lightbox-image" class="img-responsive" src="'+a+'"><div id="lightbox-video-container" class="embed-responsive embed-responsive-16by9"><video controls '+
f+' class="embed-responsive-item"><source id="lightbox-video" src="'+a+'" type="video/mp4"></video></div>'+c+"</div></div></div></div>");$("body").append(b);"fullscreen-lb"==e&&($("#lightbox-modal").b("fullscreen-modal").append('<a class="close-full-screen-modal animated fadeIn" style="animation-delay:0.5s;" onclick="$(\'#lightbox-modal\').modal(\'hide\');"><div class="close-icon"></div></a>'),$("#blocs-lightbox-close-btn").remove());".mp4"==a.substring(a.length-4)?($("#lightbox-image, .lightbox-caption").g(),
$("#lightbox-video-container").show()):($("#lightbox-image,.lightbox-caption").show(),$("#lightbox-video-container").g());$("#lightbox-modal").D("show");"no-gallery-set"==d?(0==$("a[data-lightbox]").index(targetLightbox)&&$(".prev-lightbox").g(),$("a[data-lightbox]").index(targetLightbox)==$("a[data-lightbox]").length-1&&$(".next-lightbox").g()):(0==$('a[data-gallery-id="'+d+'"]').index(targetLightbox)&&$(".prev-lightbox").g(),$('a[data-gallery-id="'+d+'"]').index(targetLightbox)==$('a[data-gallery-id="'+
d+'"]').length-1&&$(".next-lightbox").g());v()}).j("hidden.bs.modal","#lightbox-modal",function(){$("#lightbox-modal").remove()});$(document).j("click",".next-lightbox, .prev-lightbox",function(a){a.preventDefault();a="no-gallery-set";var b=$("a[data-lightbox]").index(targetLightbox),c=$("a[data-lightbox]").l(b+1);targetLightbox.a("data-gallery-id")&&(a=targetLightbox.a("data-gallery-id"),b=$('a[data-gallery-id="'+a+'"]').index(targetLightbox),c=$('a[data-gallery-id="'+a+'"]').l(b+1));$(this).f("prev-lightbox")&&
(c=$('a[data-gallery-id="'+a+'"]').l(b-1),"no-gallery-set"==a&&(c=$("a[data-lightbox]").l(b-1)));b=c.a("data-lightbox");if(".mp4"==b.substring(b.length-4)){var d="";1==c.a("data-autoplay")&&(d="autoplay");$("#lightbox-image, .lightbox-caption").g();$("#lightbox-video-container").show().s("<video controls "+d+' class="embed-responsive-item"><source id="lightbox-video" src="'+b+'" type="video/mp4"></video>')}else $("#lightbox-image").a("src",b).show(),$(".lightbox-caption").s(c.a("data-caption")).show(),
$("#lightbox-video-container").g();targetLightbox=c;$(".next-lightbox, .prev-lightbox").g();"no-gallery-set"==a?($("a[data-lightbox]").index(c)!=$("a[data-lightbox]").length-1&&$(".next-lightbox").show(),0<$("a[data-lightbox]").index(c)&&$(".prev-lightbox").show()):($('a[data-gallery-id="'+a+'"]').index(c)!=$('a[data-gallery-id="'+a+'"]').length-1&&$(".next-lightbox").show(),0<$('a[data-gallery-id="'+a+'"]').index(c)&&$(".prev-lightbox").show())})}
function w(){$(".carousel-inner").length&&$(".carousel-inner").u({v:function(){$(this).parent().o("next")},A:function(){$(this).parent().o("prev")},threshold:0})}function x(){$(window).C(function(a){37==a.which?$(".prev-lightbox").is(":visible")&&$(".prev-lightbox").click():39==a.which&&$(".next-lightbox").is(":visible")&&$(".next-lightbox").click()})}
function v(){$("#lightbox-image").length&&$("#lightbox-image").u({v:function(){$(".next-lightbox").is(":visible")&&$(".next-lightbox").click()},A:function(){$(".prev-lightbox").is(":visible")&&$(".prev-lightbox").click()},threshold:0})}
$(document).ready(function(){$("#scroll-hero").click(function(a){a.preventDefault();$("html,body").animate({scrollTop:$("#scroll-hero").closest(".bloc").height()},"slow")});k();h();r();u();t();w();x();-1!=navigator.userAgent.indexOf("Safari")&&-1==navigator.userAgent.indexOf("Chrome")&&$("#page-loading-blocs-notifaction").remove()});$(window).load(function(){l();n();$("#page-loading-blocs-notifaction").remove()}).resize(function(){l()});$(function(){$('[data-toggle="tooltip"]').K()});