/*
 Bootstrap v3.3.5 (http://getbootstrap.com)
 Copyright 2011-2015 Twitter, Inc.
 Licensed under the MIT license
*/
if("undefined"==typeof jQuery)throw Error("Bootstrap's JavaScript requires jQuery");var p=jQuery.b.Nb.split(" ")[0].split(".");if(2>p[0]&&9>p[1]||1==p[0]&&9==p[1]&&1>p[2])throw Error("Bootstrap's JavaScript requires jQuery version 1.9.1 or higher");NaN;
+function(c){function g(){var l=document.createElement("bootstrap"),f={WebkitTransition:"webkitTransitionEnd",MozTransition:"transitionend",Cb:"oTransitionEnd otransitionend",transition:"transitionend"},a;for(a in f)if(void 0!==l.style[a])return{end:f[a]};return!1}c.b.H=function(l){var f=!1,a=this;c(this).u("bsTransitionEnd",function(){f=!0});return setTimeout(function(){f||c(a).c(c.s.transition.end)},l),this};c(function(){c.s.transition=g();c.s.transition&&(c.event.Tb.Eb={Db:c.s.transition.end,Gb:c.s.transition.end,
Hb:function(l){return c(l.target).is(this)?l.Ib.Jb.apply(this,arguments):void 0}})})}(jQuery);
+function(c){function g(f){c(f).g("click",'[data-dismiss="alert"]',this.close)}g.VERSION="3.3.5";g.v=150;g.prototype.close=function(f){function a(){d.detach().c("closed.bs.alert").remove()}var b=c(this),e=b.f("data-target");e||(e=b.f("href"),e=e&&e.replace(/.*(?=#[^\s]*$)/,""));var d=c(e);f&&f.preventDefault();d.length||(d=b.closest(".alert"));d.c(f=c.Event("close.bs.alert"));f.B()||(d.i("in"),c.s.transition&&d.j("fade")?d.u("bsTransitionEnd",a).H(g.v):a())};var l=c.b.alert;c.b.alert=function(f){return this.o(function(){var a=
c(this),b=a.data("bs.alert");b||a.data("bs.alert",b=new g(this));"string"==typeof f&&b[f].call(a)})};c.b.alert.F=g;c.b.alert.L=function(){return c.b.alert=l,this};c(document).g("click.bs.alert.data-api",'[data-dismiss="alert"]',g.prototype.close)}(jQuery);
+function(c){function g(a,b){this.a=c(a);this.options=c.extend({},g.m,b);this.Da=!1}function l(a){return this.o(function(){var b=c(this),e=b.data("bs.button"),d="object"==typeof a&&a;e||b.data("bs.button",e=new g(this,d));"toggle"==a?e.toggle():a&&e.Ab(a)})}g.VERSION="3.3.5";g.m={Ob:"loading..."};g.prototype.Ab=function(a){var b=this.a,e=b.is("input")?"val":"html",d=b.data();a+="Text";null==d.Rb&&b.data("resetText",b[e]());setTimeout(c.l(function(){b[e](null==d[a]?this.options[a]:d[a]);"loadingText"==
a?(this.Da=!0,b.h("disabled").f("disabled","disabled")):this.Da&&(this.Da=!1,b.i("disabled").ub("disabled"))},this),0)};g.prototype.toggle=function(){var a=!0,b=this.a.closest('[data-toggle="buttons"]');if(b.length){var e=this.a.find("input");"radio"==e.ja("type")?(e.ja("checked")&&(a=!1),b.find(".active").i("active"),this.a.h("active")):"checkbox"==e.ja("type")&&(e.ja("checked")!==this.a.j("active")&&(a=!1),this.a.na("active"));e.ja("checked",this.a.j("active"));a&&e.c("change")}else this.a.f("aria-pressed",
!this.a.j("active")),this.a.na("active")};var f=c.b.button;c.b.button=l;c.b.button.F=g;c.b.button.L=function(){return c.b.button=f,this};c(document).g("click.bs.button.data-api",'[data-toggle^="button"]',function(a){var b=c(a.target);b.j("btn")||(b=b.closest(".btn"));l.call(b,"toggle");c(a.target).is('input[type="radio"]')||c(a.target).is('input[type="checkbox"]')||a.preventDefault()}).g("focus.bs.button.data-api blur.bs.button.data-api",'[data-toggle^="button"]',function(a){c(a.target).closest(".btn").na("focus",
/^focus(in)?$/.test(a.type))})}(jQuery);
+function(c){function g(b){var e,d=c(this),h=c(d.f("data-target")||(e=d.f("href"))&&e.replace(/.*(?=#[^\s]+$)/,""));h.j("carousel")&&(e=c.extend({},h.data(),d.data()),(d=d.f("data-slide-to"))&&(e.interval=!1),f.call(h,e),d&&h.data("bs.carousel").Ha(d),b.preventDefault())}function l(b,e){this.a=c(b);this.qa=this.a.find(".carousel-indicators");this.options=e;this.N=this.Ja=this.interval=this.P=this.paused=null;this.options.keyboard&&this.a.g("keydown.bs.carousel",c.l(this.ea,this));"hover"!=this.options.pause||
"ontouchstart"in document.documentElement||this.a.g("mouseenter.bs.carousel",c.l(this.pause,this)).g("mouseleave.bs.carousel",c.l(this.Z,this))}function f(b){return this.o(function(){var e=c(this),d=e.data("bs.carousel"),h=c.extend({},l.m,e.data(),"object"==typeof b&&b),k="string"==typeof b?b:h.ma;d||e.data("bs.carousel",d=new l(this,h));"number"==typeof b?d.Ha(b):k?d[k]():h.interval&&d.pause().Z()})}l.VERSION="3.3.5";l.v=600;l.m={interval:5E3,pause:"hover",Bb:!0,keyboard:!0};l.prototype.ea=function(b){if(!/input|textarea/i.test(b.target.tagName)){switch(b.which){case 37:this.tb();
break;case 39:this.next();break;default:return}b.preventDefault()}};l.prototype.Z=function(b){return b||(this.paused=!1),this.interval&&clearInterval(this.interval),this.options.interval&&!this.paused&&(this.interval=setInterval(c.l(this.next,this),this.options.interval)),this};l.prototype.Aa=function(b){return this.N=b.parent().children(".item"),this.N.index(b||this.Ja)};l.prototype.kb=function(b,e){var d=this.Aa(e);return("prev"==b&&0===d||"next"==b&&d==this.N.length-1)&&!this.options.Bb?e:this.N.Ua((d+
("prev"==b?-1:1))%this.N.length)};l.prototype.Ha=function(b){var e=this,d=this.Aa(this.Ja=this.a.find(".item.active"));b>this.N.length-1||0>b||(this.P?this.a.u("slid.bs.carousel",function(){e.Ha(b)}):d==b?this.pause().Z():this.ma(b>d?"next":"prev",this.N.Ua(b)))};l.prototype.pause=function(b){return b||(this.paused=!0),this.a.find(".next, .prev").length&&c.s.transition&&(this.a.c(c.s.transition.end),this.Z(!0)),this.interval=clearInterval(this.interval),this};l.prototype.next=function(){return this.P?
void 0:this.ma("next")};l.prototype.tb=function(){this.P||this.ma("prev")};l.prototype.ma=function(b,e){var d=this.a.find(".item.active"),h=e||this.kb(b,d),k=this.interval,m="next"==b?"left":"right",n=this;if(h.j("active"))return this.P=!1;var q=h[0],r=c.Event("slide.bs.carousel",{relatedTarget:q,direction:m});if(this.a.c(r),!r.B()){if(this.P=!0,k&&this.pause(),this.qa.length)this.qa.find(".active").i("active"),(r=c(this.qa.children()[this.Aa(h)]))&&r.h("active");var t=c.Event("slid.bs.carousel",
{relatedTarget:q,direction:m});return c.s.transition&&this.a.j("slide")?(h.h(b),h[0].offsetWidth,d.h(m),h.h(m),d.u("bsTransitionEnd",function(){h.i([b,m].join(" ")).h("active");d.i(["active",m].join(" "));n.P=!1;setTimeout(function(){n.a.c(t)},0)}).H(l.v)):(d.i("active"),h.h("active"),this.P=!1,this.a.c(t)),k&&this.Z(),this}};var a=c.b.aa;c.b.aa=f;c.b.aa.F=l;c.b.aa.L=function(){return c.b.aa=a,this};c(document).g("click.bs.carousel.data-api","[data-slide]",g).g("click.bs.carousel.data-api","[data-slide-to]",
g);c(window).g("load",function(){c('[data-ride="carousel"]').o(function(){var b=c(this);f.call(b,b.data())})})}(jQuery);
+function(c){function g(b,e){this.a=c(b);this.options=c.extend({},g.m,e);this.sa=c('[data-toggle="collapse"][href="#'+b.id+'"],[data-toggle="collapse"][data-target="#'+b.id+'"]');this.S=null;this.options.parent?this.Ka=this.getParent():this.Oa(this.a,this.sa);this.options.toggle&&this.toggle()}function l(b){var e;b=b.f("data-target")||(e=b.f("href"))&&e.replace(/.*(?=#[^\s]+$)/,"");return c(b)}function f(b){return this.o(function(){var e=c(this),d=e.data("bs.collapse"),h=c.extend({},g.m,e.data(),
"object"==typeof b&&b);!d&&h.toggle&&/show|hide/.test(b)&&(h.toggle=!1);d||e.data("bs.collapse",d=new g(this,h));"string"==typeof b&&d[b]()})}g.VERSION="3.3.5";g.v=350;g.m={toggle:!0};g.prototype.Ta=function(){return this.a.j("width")?"width":"height"};g.prototype.show=function(){if(!this.S&&!this.a.j("in")){var b,e=this.Ka&&this.Ka.children(".panel").children(".in, .collapsing");if(!(e&&e.length&&(b=e.data("bs.collapse"),b&&b.S))){var d=c.Event("show.bs.collapse");if(this.a.c(d),!d.B()){e&&e.length&&
(f.call(e,"hide"),b||e.data("bs.collapse",null));var h=this.Ta();this.a.i("collapse").h("collapsing")[h](0).f("aria-expanded",!0);this.sa.i("collapsed").f("aria-expanded",!0);this.S=1;b=function(){this.a.i("collapsing").h("collapse in")[h]("");this.S=0;this.a.c("shown.bs.collapse")};if(!c.s.transition)return b.call(this);e=c.Fb(["scroll",h].join("-"));this.a.u("bsTransitionEnd",c.l(b,this)).H(g.v)[h](this.a[0][e])}}}};g.prototype.A=function(){if(!this.S&&this.a.j("in")){var b=c.Event("hide.bs.collapse");
if(this.a.c(b),!b.B()){b=this.Ta();this.a[b](this.a[b]())[0].offsetHeight;this.a.h("collapsing").i("collapse in").f("aria-expanded",!1);this.sa.h("collapsed").f("aria-expanded",!1);this.S=1;var e=function(){this.S=0;this.a.i("collapsing").h("collapse").c("hidden.bs.collapse")};return c.s.transition?void this.a[b](0).u("bsTransitionEnd",c.l(e,this)).H(g.v):e.call(this)}}};g.prototype.toggle=function(){this[this.a.j("in")?"hide":"show"]()};g.prototype.getParent=function(){return c(this.options.parent).find('[data-toggle="collapse"][data-parent="'+
this.options.parent+'"]').o(c.l(function(b,e){var d=c(e);this.Oa(l(d),d)},this)).end()};g.prototype.Oa=function(b,e){var d=b.j("in");b.f("aria-expanded",d);e.na("collapsed",!d).f("aria-expanded",d)};var a=c.b.collapse;c.b.collapse=f;c.b.collapse.F=g;c.b.collapse.L=function(){return c.b.collapse=a,this};c(document).g("click.bs.collapse.data-api",'[data-toggle="collapse"]',function(b){var e=c(this);e.f("data-target")||b.preventDefault();b=l(e);e=b.data("bs.collapse")?"toggle":e.data();f.call(b,e)})}(jQuery);
+function(c){function g(d){c(d).g("click.bs.dropdown",this.toggle)}function l(d){var h=d.f("data-target");h||(h=d.f("href"),h=h&&/#[A-Za-z]/.test(h)&&h.replace(/.*(?=#[^\s]*$)/,""));return(h=h&&c(h))&&h.length?h:d.parent()}function f(d){d&&3===d.which||(c(a).remove(),c(b).o(function(){var h=c(this),k=l(h),m={relatedTarget:this};k.j("open")&&(d&&"click"==d.type&&/input|textarea/i.test(d.target.tagName)&&c.contains(k[0],d.target)||(k.c(d=c.Event("hide.bs.dropdown",m)),d.B()||(h.f("aria-expanded","false"),
k.i("open").c("hidden.bs.dropdown",m))))}))}var a=".dropdown-backdrop",b='[data-toggle="dropdown"]';g.VERSION="3.3.5";g.prototype.toggle=function(d){var h=c(this);if(!h.is(".disabled, :disabled")){var k=l(h),m=k.j("open");if(f(),!m){"ontouchstart"in document.documentElement&&!k.closest(".navbar-nav").length&&c(document.createElement("div")).h("dropdown-backdrop").qb(c(this)).g("click",f);m={relatedTarget:this};if(k.c(d=c.Event("show.bs.dropdown",m)),d.B())return;h.c("focus").f("aria-expanded","true");
k.na("open").c("shown.bs.dropdown",m)}return!1}};g.prototype.ea=function(d){if(/(38|40|27|32)/.test(d.which)&&!/input|textarea/i.test(d.target.tagName)){var h=c(this);if(d.preventDefault(),d.stopPropagation(),!h.is(".disabled, :disabled")){var k=l(h),m=k.j("open");if(!m&&27!=d.which||m&&27==d.which)return 27==d.which&&k.find(b).c("focus"),h.c("click");h=k.find(".dropdown-menu li:not(.disabled):visible a");h.length&&(k=h.index(d.target),38==d.which&&0<k&&k--,40==d.which&&k<h.length-1&&k++,~k||(k=0),
h.Ua(k).c("focus"))}}};var e=c.b.ba;c.b.ba=function(d){return this.o(function(){var h=c(this),k=h.data("bs.dropdown");k||h.data("bs.dropdown",k=new g(this));"string"==typeof d&&k[d].call(h)})};c.b.ba.F=g;c.b.ba.L=function(){return c.b.ba=e,this};c(document).g("click.bs.dropdown.data-api",f).g("click.bs.dropdown.data-api",".dropdown form",function(d){d.stopPropagation()}).g("click.bs.dropdown.data-api",b,g.prototype.toggle).g("keydown.bs.dropdown.data-api",b,g.prototype.ea).g("keydown.bs.dropdown.data-api",
".dropdown-menu",g.prototype.ea)}(jQuery);
+function(c){function g(a,b){this.options=b;this.D=c(document.body);this.a=c(a);this.pa=this.a.find(".modal-dialog");this.ab=this.K=this.I=null;this.ka=0;this.Ca=!1;this.options.remote&&this.a.find(".modal-content").load(this.options.remote,c.l(function(){this.a.c("loaded.bs.modal")},this))}function l(a,b){return this.o(function(){var e=c(this),d=e.data("bs.modal"),h=c.extend({},g.m,e.data(),"object"==typeof a&&a);d||e.data("bs.modal",d=new g(this,h));"string"==typeof a?d[a](b):h.show&&d.show(b)})}
g.VERSION="3.3.5";g.v=300;g.La=150;g.m={Y:!0,keyboard:!0,show:!0};g.prototype.toggle=function(a){return this.K?this.A():this.show(a)};g.prototype.show=function(a){var b=this,e=c.Event("show.bs.modal",{relatedTarget:a});this.a.c(e);this.K||e.B()||(this.K=!0,this.gb(),this.zb(),this.D.h("modal-open"),this.escape(),this.resize(),this.a.g("click.dismiss.bs.modal",'[data-dismiss="modal"]',c.l(this.A,this)),this.pa.g("mousedown.dismiss.bs.modal",function(){b.a.u("mouseup.dismiss.bs.modal",function(d){c(d.target).is(b.a)&&
(b.Ca=!0)})}),this.Y(function(){var d=c.s.transition&&b.a.j("fade");b.a.parent().length||b.a.Qa(b.D);b.a.show().scrollTop(0);b.Pa();d&&b.a[0].offsetWidth;b.a.h("in");b.hb();var h=c.Event("shown.bs.modal",{relatedTarget:a});d?b.pa.u("bsTransitionEnd",function(){b.a.c("focus").c(h)}).H(g.v):b.a.c("focus").c(h)}))};g.prototype.A=function(a){a&&a.preventDefault();a=c.Event("hide.bs.modal");this.a.c(a);this.K&&!a.B()&&(this.K=!1,this.escape(),this.resize(),c(document).U("focusin.bs.modal"),this.a.i("in").U("click.dismiss.bs.modal").U("mouseup.dismiss.bs.modal"),
this.pa.U("mousedown.dismiss.bs.modal"),c.s.transition&&this.a.j("fade")?this.a.u("bsTransitionEnd",c.l(this.Ya,this)).H(g.v):this.Ya())};g.prototype.hb=function(){c(document).U("focusin.bs.modal").g("focusin.bs.modal",c.l(function(a){this.a[0]===a.target||this.a.has(a.target).length||this.a.c("focus")},this))};g.prototype.escape=function(){this.K&&this.options.keyboard?this.a.g("keydown.dismiss.bs.modal",c.l(function(a){27==a.which&&this.A()},this)):this.K||this.a.U("keydown.dismiss.bs.modal")};
g.prototype.resize=function(){this.K?c(window).g("resize.bs.modal",c.l(this.pb,this)):c(window).U("resize.bs.modal")};g.prototype.Ya=function(){var a=this;this.a.A();this.Y(function(){a.D.i("modal-open");a.xb();a.yb();a.a.c("hidden.bs.modal")})};g.prototype.vb=function(){this.I&&this.I.remove();this.I=null};g.prototype.Y=function(a){var b=this,e=this.a.j("fade")?"fade":"";if(this.K&&this.options.Y){var d=c.s.transition&&e;if(this.I=c(document.createElement("div")).h("modal-backdrop "+e).Qa(this.D),
this.a.g("click.dismiss.bs.modal",c.l(function(h){return this.Ca?void(this.Ca=!1):void(h.target===h.currentTarget&&("static"==this.options.Y?this.a[0].focus():this.A()))},this)),d&&this.I[0].offsetWidth,this.I.h("in"),a)d?this.I.u("bsTransitionEnd",a).H(g.La):a()}else!this.K&&this.I?(this.I.i("in"),e=function(){b.vb();a&&a()},c.s.transition&&this.a.j("fade")?this.I.u("bsTransitionEnd",e).H(g.La):e()):a&&a()};g.prototype.pb=function(){this.Pa()};g.prototype.Pa=function(){var a=this.a[0].scrollHeight>
document.documentElement.clientHeight;this.a.G({paddingLeft:!this.va&&a?this.ka:"",paddingRight:this.va&&!a?this.ka:""})};g.prototype.xb=function(){this.a.G({paddingLeft:"",paddingRight:""})};g.prototype.gb=function(){var a=window.innerWidth;a||(a=document.documentElement.getBoundingClientRect(),a=a.right-Math.abs(a.left));this.va=document.body.clientWidth<a;this.ka=this.rb()};g.prototype.zb=function(){var a=parseInt(this.D.G("padding-right")||0,10);this.ab=document.body.style.paddingRight||"";this.va&&
this.D.G("padding-right",a+this.ka)};g.prototype.yb=function(){this.D.G("padding-right",this.ab)};g.prototype.rb=function(){var a=document.createElement("div");a.className="modal-scrollbar-measure";this.D.append(a);var b=a.offsetWidth-a.clientWidth;return this.D[0].removeChild(a),b};var f=c.b.ga;c.b.ga=l;c.b.ga.F=g;c.b.ga.L=function(){return c.b.ga=f,this};c(document).g("click.bs.modal.data-api",'[data-toggle="modal"]',function(a){var b=c(this),e=b.f("href"),d=c(b.f("data-target")||e&&e.replace(/.*(?=#[^\s]+$)/,
""));e=d.data("bs.modal")?"toggle":c.extend({remote:!/#/.test(e)&&e},d.data(),b.data());b.is("a")&&a.preventDefault();d.u("show.bs.modal",function(h){h.B()||d.u("hidden.bs.modal",function(){b.is(":visible")&&b.c("focus")})});l.call(d,e,this)})}(jQuery);
+function(c){function g(f,a){this.O=this.a=this.J=this.timeout=this.enabled=this.options=this.type=null;this.Za("tooltip",f,a)}g.VERSION="3.3.5";g.v=150;g.m={animation:!0,ha:"top",C:!1,cb:'<div class="tooltip" role="tooltip"><div class="tooltip-arrow"></div><div class="tooltip-inner"></div></div>',c:"hover focus",title:"",delay:0,da:!1,Sa:!1,viewport:{C:"body",padding:0}};g.prototype.Za=function(f,a,b){if(this.enabled=!0,this.type=f,this.a=c(a),this.options=this.lb(b),this.ta=this.options.viewport&&
c(c.Lb(this.options.viewport)?this.options.viewport.call(this,this.a):this.options.viewport.C||this.options.viewport),this.O={click:!1,Kb:!1,focus:!1},this.a[0]instanceof document.constructor&&!this.options.C)throw Error("`selector` option must be specified when initializing "+this.type+" on the window.document object!");f=this.options.c.split(" ");for(a=f.length;a--;)if(b=f[a],"click"==b)this.a.g("click."+this.type,this.options.C,c.l(this.toggle,this));else if("manual"!=b){var e="hover"==b?"mouseleave":
"focusout";this.a.g(("hover"==b?"mouseenter":"focusin")+"."+this.type,this.options.C,c.l(this.xa,this));this.a.g(e+"."+this.type,this.options.C,c.l(this.fa,this))}this.options.C?this.Na=c.extend({},this.options,{c:"manual",C:""}):this.ib()};g.prototype.ya=function(){return g.m};g.prototype.lb=function(f){return f=c.extend({},this.ya(),this.a.data(),f),f.delay&&"number"==typeof f.delay&&(f.delay={show:f.delay,A:f.delay}),f};g.prototype.za=function(){var f={},a=this.ya();return this.Na&&c.o(this.Na,
function(b,e){a[b]!=e&&(f[b]=e)}),f};g.prototype.xa=function(f){var a=f instanceof this.constructor?f:c(f.currentTarget).data("bs."+this.type);return a||(a=new this.constructor(f.currentTarget,this.za()),c(f.currentTarget).data("bs."+this.type,a)),f instanceof c.Event&&(a.O["focusin"==f.type?"focus":"hover"]=!0),a.M().j("in")||"in"==a.J?void(a.J="in"):(clearTimeout(a.timeout),a.J="in",a.options.delay&&a.options.delay.show?void(a.timeout=setTimeout(function(){"in"==a.J&&a.show()},a.options.delay.show)):
a.show())};g.prototype.$a=function(){for(var f in this.O)if(this.O[f])return!0;return!1};g.prototype.fa=function(f){var a=f instanceof this.constructor?f:c(f.currentTarget).data("bs."+this.type);return a||(a=new this.constructor(f.currentTarget,this.za()),c(f.currentTarget).data("bs."+this.type,a)),f instanceof c.Event&&(a.O["focusout"==f.type?"focus":"hover"]=!1),a.$a()?void 0:(clearTimeout(a.timeout),a.J="out",a.options.delay&&a.options.delay.A?void(a.timeout=setTimeout(function(){"out"==a.J&&a.A()},
a.options.delay.A)):a.A())};g.prototype.show=function(){var f=c.Event("show.bs."+this.type);if(this.Xa()&&this.enabled){this.a.c(f);var a=c.contains(this.a[0].ownerDocument.documentElement,this.a[0]);if(!f.B()&&a){var b=this;f=this.M();a=this.nb(this.type);this.bb();f.f("id",a);this.a.f("aria-describedby",a);this.options.animation&&f.h("fade");a="function"==typeof this.options.ha?this.options.ha.call(this,f[0],this.a[0]):this.options.ha;var e=/\s?auto?\s?/i,d=e.test(a);d&&(a=a.replace(e,"")||"top");
f.detach().G({top:0,left:0,display:"block"}).h(a).data("bs."+this.type,this);this.options.Sa?f.Qa(this.options.Sa):f.qb(this.a);this.a.c("inserted.bs."+this.type);e=this.Ba();var h=f[0].offsetWidth,k=f[0].offsetHeight;if(d){d=a;var m=this.Ba(this.ta);a="bottom"==a&&e.bottom+k>m.bottom?"top":"top"==a&&e.top-k<m.top?"bottom":"right"==a&&e.right+h>m.width?"left":"left"==a&&e.left-h<m.left?"right":a;f.i(d).h(a)}this.eb(this.jb(a,e,h,k),a);a=function(){var n=b.J;b.a.c("shown.bs."+b.type);b.J=null;"out"==
n&&b.fa(b)};c.s.transition&&this.V.j("fade")?f.u("bsTransitionEnd",a).H(g.v):a()}}};g.prototype.eb=function(f,a){var b=this.M(),e=b[0].offsetWidth,d=b[0].offsetHeight,h=parseInt(b.G("margin-top"),10),k=parseInt(b.G("margin-left"),10);isNaN(h)&&(h=0);isNaN(k)&&(k=0);f.top+=h;f.left+=k;c.offset.Sb(b[0],c.extend({Ub:function(q){b.G({top:Math.round(q.top),left:Math.round(q.left)})}},f),0);b.h("in");k=b[0].offsetWidth;var m=b[0].offsetHeight;"top"==a&&m!=d&&(f.top=f.top+d-m);var n=this.ob(a,f,k,m);n.left?
f.left+=n.left:f.top+=n.top;e=(h=/top|bottom/.test(a))?2*n.left-e+k:2*n.top-d+m;d=h?"offsetWidth":"offsetHeight";b.offset(f);this.wb(e,b[0][d],h)};g.prototype.wb=function(f,a,b){this.Ra().G(b?"left":"top",50*(1-f/a)+"%").G(b?"top":"left","")};g.prototype.bb=function(){var f=this.M(),a=this.ca();f.find(".tooltip-inner")[this.options.da?"html":"text"](a);f.i("fade in top bottom left right")};g.prototype.A=function(f){function a(){"in"!=b.J&&e.detach();b.a.ub("aria-describedby").c("hidden.bs."+b.type);
f&&f()}var b=this,e=c(this.V),d=c.Event("hide.bs."+this.type);return this.a.c(d),d.B()?void 0:(e.i("in"),c.s.transition&&e.j("fade")?e.u("bsTransitionEnd",a).H(g.v):a(),this.J=null,this)};g.prototype.ib=function(){var f=this.a;(f.f("title")||"string"!=typeof f.f("data-original-title"))&&f.f("data-original-title",f.f("title")||"").f("title","")};g.prototype.Xa=function(){return this.ca()};g.prototype.Ba=function(f){f=f||this.a;var a=f[0],b="BODY"==a.tagName;a=a.getBoundingClientRect();null==a.width&&
(a=c.extend({},a,{width:a.right-a.left,height:a.bottom-a.top}));var e=b?{top:0,left:0}:f.offset();f={scroll:b?document.documentElement.scrollTop||document.body.scrollTop:f.scrollTop()};b=b?{width:c(window).width(),height:c(window).height()}:null;return c.extend({},a,f,b,e)};g.prototype.jb=function(f,a,b,e){return"bottom"==f?{top:a.top+a.height,left:a.left+a.width/2-b/2}:"top"==f?{top:a.top-e,left:a.left+a.width/2-b/2}:"left"==f?{top:a.top+a.height/2-e/2,left:a.left-b}:{top:a.top+a.height/2-e/2,left:a.left+
a.width}};g.prototype.ob=function(f,a,b,e){var d={top:0,left:0};if(!this.ta)return d;var h=this.options.viewport&&this.options.viewport.padding||0,k=this.Ba(this.ta);/right|left/.test(f)?(b=a.top-h-k.scroll,a=a.top+h-k.scroll+e,b<k.top?d.top=k.top-b:a>k.top+k.height&&(d.top=k.top+k.height-a)):(e=a.left-h,a=a.left+h+b,e<k.left?d.left=k.left-e:a>k.right&&(d.left=k.left+k.width-a));return d};g.prototype.ca=function(){var f=this.a,a=this.options;return f.f("data-original-title")||("function"==typeof a.title?
a.title.call(f[0]):a.title)};g.prototype.nb=function(f){do f+=~~(1E6*Math.random());while(document.getElementById(f));return f};g.prototype.M=function(){if(!this.V&&(this.V=c(this.options.cb),1!=this.V.length))throw Error(this.type+" `template` option must consist of exactly 1 top-level element!");return this.V};g.prototype.Ra=function(){return this.oa=this.oa||this.M().find(".tooltip-arrow")};g.prototype.enable=function(){this.enabled=!0};g.prototype.disable=function(){this.enabled=!1};g.prototype.toggle=
function(f){var a=this;f&&(a=c(f.currentTarget).data("bs."+this.type),a||(a=new this.constructor(f.currentTarget,this.za()),c(f.currentTarget).data("bs."+this.type,a)));f?(a.O.click=!a.O.click,a.$a()?a.xa(a):a.fa(a)):a.M().j("in")?a.fa(a):a.xa(a)};var l=c.b.R;c.b.R=function(f){return this.o(function(){var a=c(this),b=a.data("bs.tooltip"),e="object"==typeof f&&f;!b&&/destroy|hide/.test(f)||(b||a.data("bs.tooltip",b=new g(this,e)),"string"!=typeof f||b[f]())})};c.b.R.F=g;c.b.R.L=function(){return c.b.R=
l,this}}(jQuery);
+function(c){function g(f,a){this.Za("popover",f,a)}if(!c.b.R)throw Error("Popover requires tooltip.js");g.VERSION="3.3.5";g.m=c.extend({},c.b.R.F.m,{ha:"right",c:"click",content:"",cb:'<div class="popover" role="tooltip"><div class="arrow"></div><h3 class="popover-title"></h3><div class="popover-content"></div></div>'});g.prototype=c.extend({},c.b.R.F.prototype);g.prototype.constructor=g;g.prototype.ya=function(){return g.m};g.prototype.bb=function(){var f=this.M(),a=this.ca(),b=this.Va();f.find(".popover-title")[this.options.da?
"html":"text"](a);f.find(".popover-content").children().detach().end()[this.options.da?"string"==typeof b?"html":"append":"text"](b);f.i("fade top bottom left right in");f.find(".popover-title").da()||f.find(".popover-title").A()};g.prototype.Xa=function(){return this.ca()||this.Va()};g.prototype.Va=function(){var f=this.a,a=this.options;return f.f("data-content")||("function"==typeof a.content?a.content.call(f[0]):a.content)};g.prototype.Ra=function(){return this.oa=this.oa||this.M().find(".arrow")};
var l=c.b.ia;c.b.ia=function(f){return this.o(function(){var a=c(this),b=a.data("bs.popover"),e="object"==typeof f&&f;!b&&/destroy|hide/.test(f)||(b||a.data("bs.popover",b=new g(this,e)),"string"!=typeof f||b[f]())})};c.b.ia.F=g;c.b.ia.L=function(){return c.b.ia=l,this}}(jQuery);
+function(c){function g(a,b){this.D=c(document.body);this.T=c(c(a).is(document.body)?window:a);this.options=c.extend({},g.m,b);this.C=(this.options.target||"")+" .nav li > a";this.Ea=[];this.Ga=[];this.ua=null;this.scrollHeight=0;this.T.g("scroll.bs.scrollspy",c.l(this.process,this));this.refresh();this.process()}function l(a){return this.o(function(){var b=c(this),e=b.data("bs.scrollspy"),d="object"==typeof a&&a;e||b.data("bs.scrollspy",e=new g(this,d));"string"==typeof a&&e[a]()})}g.VERSION="3.3.5";
g.m={offset:10};g.prototype.Wa=function(){return this.T[0].scrollHeight||Math.max(this.D[0].scrollHeight,document.documentElement.scrollHeight)};g.prototype.refresh=function(){var a=this,b="offset",e=0;this.Ea=[];this.Ga=[];this.scrollHeight=this.Wa();c.Mb(this.T[0])||(b="position",e=this.T.scrollTop());this.D.find(this.C).map(function(){var d=c(this);d=d.data("target")||d.f("href");var h=/^#./.test(d)&&c(d);return h&&h.length&&h.is(":visible")&&[[h[b]().top+e,d]]||null}).sort(function(d,h){return d[0]-
h[0]}).o(function(){a.Ea.push(this[0]);a.Ga.push(this[1])})};g.prototype.process=function(){var a,b=this.T.scrollTop()+this.options.offset,e=this.Wa(),d=this.options.offset+e-this.T.height(),h=this.Ea,k=this.Ga,m=this.ua;if(this.scrollHeight!=e&&this.refresh(),b>=d)return m!=(a=k[k.length-1])&&this.W(a);if(m&&b<h[0])return this.ua=null,this.clear();for(a=h.length;a--;)m!=k[a]&&b>=h[a]&&(void 0===h[a+1]||b<h[a+1])&&this.W(k[a])};g.prototype.W=function(a){this.ua=a;this.clear();a=c(this.C+'[data-target="'+
a+'"],'+this.C+'[href="'+a+'"]').Pb("li").h("active");a.parent(".dropdown-menu").length&&(a=a.closest("li.dropdown").h("active"));a.c("activate.bs.scrollspy")};g.prototype.clear=function(){c(this.C).Qb(this.options.target,".active").i("active")};var f=c.b.la;c.b.la=l;c.b.la.F=g;c.b.la.L=function(){return c.b.la=f,this};c(window).g("load.bs.scrollspy.data-api",function(){c('[data-spy="scroll"]').o(function(){var a=c(this);l.call(a,a.data())})})}(jQuery);
+function(c){function g(b){b.preventDefault();f.call(c(this),"show")}function l(b){this.element=c(b)}function f(b){return this.o(function(){var e=c(this),d=e.data("bs.tab");d||e.data("bs.tab",d=new l(this));"string"==typeof b&&d[b]()})}l.VERSION="3.3.5";l.v=150;l.prototype.show=function(){var b=this.element,e=b.closest("ul:not(.dropdown-menu)"),d=b.data("target");if(d||(d=b.f("href"),d=d&&d.replace(/.*(?=#[^\s]*$)/,"")),!b.parent("li").j("active")){var h=e.find(".active:last a"),k=c.Event("hide.bs.tab",
{relatedTarget:b[0]}),m=c.Event("show.bs.tab",{relatedTarget:h[0]});(h.c(k),b.c(m),m.B()||k.B())||(d=c(d),this.W(b.closest("li"),e),this.W(d,d.parent(),function(){h.c({type:"hidden.bs.tab",relatedTarget:b[0]});b.c({type:"shown.bs.tab",relatedTarget:h[0]})}))}};l.prototype.W=function(b,e,d){function h(){k.i("active").find("> .dropdown-menu > .active").i("active").end().find('[data-toggle="tab"]').f("aria-expanded",!1);b.h("active").find('[data-toggle="tab"]').f("aria-expanded",!0);m?(b[0].offsetWidth,
b.h("in")):b.i("fade");b.parent(".dropdown-menu").length&&b.closest("li.dropdown").h("active").end().find('[data-toggle="tab"]').f("aria-expanded",!0);d&&d()}var k=e.find("> .active"),m=d&&c.s.transition&&(k.length&&k.j("fade")||!!e.find("> .fade").length);k.length&&m?k.u("bsTransitionEnd",h).H(l.v):h();k.i("in")};var a=c.b.tab;c.b.tab=f;c.b.tab.F=l;c.b.tab.L=function(){return c.b.tab=a,this};c(document).g("click.bs.tab.data-api",'[data-toggle="tab"]',g).g("click.bs.tab.data-api",'[data-toggle="pill"]',
g)}(jQuery);
+function(c){function g(a,b){this.options=c.extend({},g.m,b);this.ra=c(this.options.target).g("scroll.bs.affix.data-api",c.l(this.wa,this)).g("click.bs.affix.data-api",c.l(this.fb,this));this.a=c(a);this.Fa=this.Ia=this.X=null;this.wa()}function l(a){return this.o(function(){var b=c(this),e=b.data("bs.affix"),d="object"==typeof a&&a;e||b.data("bs.affix",e=new g(this,d));"string"==typeof a&&e[a]()})}g.VERSION="3.3.5";g.Ma="affix affix-top affix-bottom";g.m={offset:0,target:window};g.prototype.getState=function(a,
b,e,d){var h=this.ra.scrollTop(),k=this.a.offset(),m=this.ra.height();if(null!=e&&"top"==this.X)return e>h?"top":!1;if("bottom"==this.X)return null!=e?h+this.Ia<=k.top?!1:"bottom":a-d>=h+m?!1:"bottom";var n=null==this.X;k=n?h:k.top;return null!=e&&e>=h?"top":null!=d&&k+(n?m:b)>=a-d?"bottom":!1};g.prototype.mb=function(){if(this.Fa)return this.Fa;this.a.i(g.Ma).h("affix");var a=this.ra.scrollTop();return this.Fa=this.a.offset().top-a};g.prototype.fb=function(){setTimeout(c.l(this.wa,this),1)};g.prototype.wa=
function(){if(this.a.is(":visible")){var a=this.a.height(),b=this.options.offset,e=b.top,d=b.bottom,h=Math.max(c(document).height(),c(document.body).height());"object"!=typeof b&&(d=e=b);"function"==typeof e&&(e=b.top(this.a));"function"==typeof d&&(d=b.bottom(this.a));b=this.getState(h,a,e,d);if(this.X!=b){null!=this.Ia&&this.a.G("top","");e="affix"+(b?"-"+b:"");var k=c.Event(e+".bs.affix");if(this.a.c(k),k.B())return;this.X=b;this.Ia="bottom"==b?this.mb():null;this.a.i(g.Ma).h(e).c(e.replace("affix",
"affixed")+".bs.affix")}"bottom"==b&&this.a.offset({top:h-a-d})}};var f=c.b.$;c.b.$=l;c.b.$.F=g;c.b.$.L=function(){return c.b.$=f,this};c(window).g("load",function(){c('[data-spy="affix"]').o(function(){var a=c(this),b=a.data();b.offset=b.offset||{};null!=b.sb&&(b.offset.bottom=b.sb);null!=b.offsetTop&&(b.offset.top=b.offsetTop);l.call(a,b)})})}(jQuery);