/*
 GMaps.js v0.4.25
 http://hpneo.github.com/gmaps/

 Copyright 2017, Gustavo Leon
 Released under the MIT License.
*/
function E(){function J(a){var b=0,c=0;if(a.getBoundingClientRect)return a=a.getBoundingClientRect(),[a.left- -(window.scrollX?window.scrollX:window.pageXOffset),a.top- -(window.scrollY?window.scrollY:window.pageYOffset)];if(a.offsetParent){do b+=a.offsetLeft,c+=a.offsetTop;while(a=a.offsetParent)}return[b,c]}function z(a,b){a=a.replace("#","");return"jQuery"in window&&b?$("#"+a,b)[0]:document.getElementById(a)}function K(a,b){var c=a.replace(".","");return"jQuery"in this&&b?$("."+c,b)[0]:document.getElementsByClassName(c)[0]}
function F(a,b){var c;if(a===b)return a;for(c in b)void 0!==b[c]&&(a[c]=b[c]);return a}var p=function(){function a(b){function c(q,u){google.a.event.addListener(q,u,function(t){void 0==t&&(t=this);b[u].apply(this,[t]);k.H()})}function f(q,u){var t="",A=window.m[k.c.id][q],w;for(w in A)A.hasOwnProperty(w)&&(t+='<li><a id="'+q+"_"+w+'" href="#">'+A[w].title+"</a></li>");if(z("gmaps_context_menu")){var B=z("gmaps_context_menu");B.innerHTML=t;t=B.getElementsByTagName("a");var L=t.length;for(w=0;w<L;w++){var H=
t[w];google.a.event.aa(H,"click");google.a.event.Fa(H,"click",function(M){M.preventDefault();A[this.id.replace(q+"_","")].action.apply(k,[u]);k.H()},!1)}w=J.apply(this,[k.c]);t=w[1]+u.na.y-15;B.style.left=w[0]+u.na.x-15+"px";B.style.top=t+"px"}}function g(q,u){return void 0===q?u:q}if("object"!==typeof window.google||!window.google.a)return"object"===typeof window.console&&window.console.error&&console.error("Google Maps API is required. Please register the following JavaScript library https://maps.googleapis.com/maps/api/js."),
function(){};if(!this)return new a(b);b.zoom=b.zoom||15;b.R=b.R||"roadmap";var k=this,h="bounds_changed center_changed click dblclick drag dragend dragstart idle maptypeid_changed projection_changed resize tilesloaded zoom_changed".split(" "),d=["mousemove","mouseout","mouseover"],n="el lat lng mapType width height markerClusterer enableNewStyle".split(" ");var l=b.c||b.ba;var x=b.la,v=google.a.Aa[b.R.toUpperCase()],y=new google.a.B(b.f,b.b),r=g(b.wa,!0),C=b.bb||{style:"DEFAULT",position:"TOP_LEFT"},
N=C.style||"DEFAULT";C=C.position||"TOP_LEFT";var O=g(b.ma,!0),P=g(b.ka,!0),Q=g(b.qa,!0),R=g(b.ta,!0),I=g(I,!0),D={};v={zoom:this.zoom,D:y,Ua:v};r={ma:O,wa:r,cb:{style:google.a.Ea[N],position:google.a.xa[C]},ka:P,qa:Q,ta:R,Wa:I};"string"===typeof b.c||"string"===typeof b.ba?-1<l.indexOf("#")?this.c=z(l,b.context):this.c=K.apply(this,[l,b.context]):this.c=l;if("undefined"===typeof this.c||null===this.c)throw"No element defined.";window.m=window.m||{};window.m[k.c.id]={};this.controls=[];this.T=[];
this.oa=[];this.zoom=b.zoom;this.g={};this.c.style.width=b.width||this.c.scrollWidth||this.c.offsetWidth;this.c.style.height=b.height||this.c.scrollHeight||this.c.offsetHeight;google.a.ab=b.Ma;for(l=0;l<n.length;l++)delete b[n[l]];1!=b.La&&(v=F(v,r));D=F(v,b);for(l=0;l<h.length;l++)delete D[h[l]];for(l=0;l<d.length;l++)delete D[d[l]];this.map=new google.a.Map(this.c,D);x&&(this.la=x.apply(this,[this.map]));this.$=function(q){f("map",q);var u=z("gmaps_context_menu");setTimeout(function(){u.style.display=
"block"},0)};this.H=function(){var q=z("gmaps_context_menu");q&&(q.style.display="none")};google.a.event.addListener(this.map,"zoom_changed",this.H);for(n=0;n<h.length;n++)x=h[n],x in b&&c(this.map,x);for(n=0;n<d.length;n++)x=d[n],x in b&&c(this.map,x);google.a.event.addListener(this.map,"rightclick",function(q){b.pa&&b.pa.apply(this,[q]);void 0!=window.m[k.c.id].map&&k.$(q)});this.refresh=function(){google.a.event.va(this.map,"resize")};h=[];for(var G in this.map)"function"!=typeof this.map[G]||
this[G]||h.push(G);for(l=0;l<h.length;l++)(function(q,u,t){q[t]=function(){return u[t].apply(u,arguments)}})(this,this.map,h[l])}return a}(this);p.prototype.ca=function(a){var b=[],c=a.path;if(c.length)if(void 0===c[0][0])b=c;else for(var f=0,g;g=c[f];f++)b.push(new google.a.B(g[0],g[1]));b={map:this.map,path:b,strokeColor:a.strokeColor,strokeOpacity:a.strokeOpacity,l:a.l,ia:a.ia,K:!0,M:!1,visible:!0};a.hasOwnProperty("clickable")&&(b.K=a.K);a.hasOwnProperty("editable")&&(b.M=a.M);a.hasOwnProperty("icons")&&
(b.I=a.I);a.hasOwnProperty("zIndex")&&(b.zIndex=a.zIndex);b=new google.a.Ba(b);c="click dblclick mousedown mousemove mouseout mouseover mouseup rightclick".split(" ");for(f=0;f<c.length;f++)(function(k,h){a[h]&&google.a.event.addListener(k,h,function(d){a[h].apply(this,[d])})})(b,c[f]);this.oa.push(b);p.fa("polyline_added",b,this);return b};p.J=function(a){this.origin=a.origin;this.destination=a.destination;this.map=a.map;this.v=a.v;this.h=0;this.A=this.v.P[0].A;this.sa=this.A.length;var b={path:new google.a.za,
strokeColor:a.strokeColor,strokeOpacity:a.strokeOpacity,l:a.l};a.hasOwnProperty("icons")&&(b.I=a.I);this.u=this.map.ca(b).Qa()};p.J.prototype.back=function(){if(0<this.h){this.h--;var a=this.v.P[0].A[this.h].path,b;for(b in a)a.hasOwnProperty(b)&&this.u.pop()}};p.J.prototype.forward=function(){if(this.h<this.sa){var a=this.v.P[0].A[this.h].path,b;for(b in a)a.hasOwnProperty(b)&&this.u.push(a[b]);this.h++}};p.Za=function(a){function b(y,r){if("#"===y[0]&&(y=y.replace("#","0x"),r)){r=parseFloat(r);
r=Math.min(1,Math.max(r,0));if(0===r)return"0x00000000";r=(255*r).toString(16);1===r.length&&(r+=r);y=y.slice(0,8)+r}return y}var c=[],f=("file:"===location.protocol?"http:":location.protocol)+"//maps.googleapis.com/maps/api/staticmap";a.url&&(f=a.url,delete a.url);f+="?";var g=a.T;delete a.T;!g&&a.S&&(g=[a.S],delete a.S);var k=a.ua;delete a.ua;var h=a.u;delete a.u;if(a.D)c.push("center="+a.D),delete a.D;else if(a.i)c.push("center="+a.i),delete a.i;else if(a.f)c.push(["center=",a.f,",",a.b].join("")),
delete a.f,delete a.b;else if(a.visible){var d=encodeURI(a.visible.join("|"));c.push("visible="+d)}(d=a.size)?(d.join&&(d=d.join("x")),delete a.size):d="630x300";c.push("size="+d);a.zoom||!1===a.zoom||(a.zoom=15);d=a.hasOwnProperty("sensor")?!!a.ra:!0;delete a.ra;c.push("sensor="+d);for(var n in a)a.hasOwnProperty(n)&&c.push(n+"="+a[n]);if(g)for(a=0;d=g[a];a++){var l=[];d.size&&"normal"!==d.size?(l.push("size:"+d.size),delete d.size):d.icon&&(l.push("icon:"+encodeURI(d.icon)),delete d.icon);d.color&&
(l.push("color:"+d.color.replace("#","0x")),delete d.color);d.label&&(l.push("label:"+d.label[0].toUpperCase()),delete d.label);var x=d.i?d.i:d.f+","+d.b;delete d.i;delete d.f;delete d.b;for(n in d)d.hasOwnProperty(n)&&l.push(n+":"+d[n]);l.length||0===a?(l.push(x),l=l.join("|"),c.push("markers="+encodeURI(l))):(l=c.pop()+encodeURI("|"+x),c.push(l))}if(k)for(a=0;a<k.length;a++){n=[];k[a].ea&&n.push("feature:"+k[a].ea.toLowerCase());k[a].da&&n.push("element:"+k[a].da.toLowerCase());for(g=0;g<k[a].X.length;g++)for(var v in k[a].X[g]){d=
k[a].X[g][v];if("hue"==v||"color"==v)d="0x"+d.substring(1);n.push(v+":"+d)}g=n.join("|");""!=g&&c.push("style="+g)}if(h){d=h;h=[];d.l&&h.push("weight:"+parseInt(d.l,10));d.strokeColor&&(k=b(d.strokeColor,d.strokeOpacity),h.push("color:"+k));d.fillColor&&(k=b(d.fillColor,d.Oa),h.push("fillcolor:"+k));k=d.path;if(k.join)for(g=0;v=k[g];g++)h.push(v.join(","));else h.push("enc:"+k);h=h.join("|");c.push("path="+encodeURI(h))}c.push("scale="+(window.devicePixelRatio||1));c=c.join("&");return f+c};p.prototype.L=
function(a){a.hasOwnProperty("lat")&&a.hasOwnProperty("lng")||(a.f=this.N().f(),a.b=this.N().b());this.W=p.L(a);this.map.Xa(this.W);return this.W};p.L=function(a){var b=z(a.c,a.context);a.position=new google.a.B(a.f,a.b);delete a.c;delete a.context;delete a.f;delete a.b;for(var c="closeclick links_changed pano_changed position_changed pov_changed resize visible_changed".split(" "),f=F({visible:!0},a),g=0;g<c.length;g++)delete f[c[g]];b=new google.a.Da(b,f);for(g=0;g<c.length;g++)(function(k,h){a[h]&&
google.a.event.addListener(k,h,function(){a[h].apply(this)})})(b,c[g]);return b};p.prototype.V=function(a,b){return p.V(a,this,b)};p.prototype.U=function(a){p.U(a,this)};p.prototype.once=function(a,b){return p.once(a,this,b)};p.o="marker_added marker_removed polyline_added polyline_removed polygon_added polygon_removed geolocated geolocation_failed".split(" ");p.V=function(a,b,c){if(-1==p.o.indexOf(a))return b instanceof p&&(b=b.map),google.a.event.addListener(b,a,c);c={Sa:c,Na:a};b.g[a]=b.g[a]||
[];b.g[a].push(c);return c};p.U=function(a,b){-1==p.o.indexOf(a)?(b instanceof p&&(b=b.map),google.a.event.aa(b,a)):b.g[a]=[]};p.once=function(a,b,c){if(-1==p.o.indexOf(a))return b instanceof p&&(b=b.map),google.a.event.Ga(b,a,c)};p.fa=function(a,b,c){if(-1==p.o.indexOf(a))google.a.event.va(b,a,Array.prototype.slice.apply(arguments).slice(2));else if(a in c.g)for(var f=c.g[a],g=0;g<f.length;g++)f[g].handler.apply(c,[b])};p.Pa=function(a){var b=a.Ha||a.complete;navigator.geolocation?navigator.geolocation.getCurrentPosition(function(c){a.$a(c);
b&&b()},function(c){a.error(c);b&&b()},a.options):(a.Va(),b&&b())};p.ga=function(a){this.ha=new google.a.ya;a.hasOwnProperty("lat")&&a.hasOwnProperty("lng")&&(a.Ta=new google.a.B(a.f,a.b));delete a.f;delete a.b;delete a.Ja;this.ha.ga(a)};"object"===typeof window.google&&window.google.a&&(google.a.C.prototype.F||(google.a.C.prototype.F=function(){for(var a=new google.a.Z,b=this.O(),c,f=0;f<b.G();f++){c=b.s(f);for(var g=0;g<c.G();g++)a.extend(c.s(g))}return a}),google.a.C.prototype.j||(google.a.C.prototype.j=
function(a){var b=this.F();if(null!==b&&!b.contains(a))return!1;b=!1;for(var c=this.O().G(),f=0;f<c;f++)for(var g=this.O().s(f),k=g.G(),h=k-1,d=0;d<k;d++){var n=g.s(d);h=g.s(h);(n.b()<a.b()&&h.b()>=a.b()||h.b()<a.b()&&n.b()>=a.b())&&n.f()+(a.b()-n.b())/(h.b()-n.b())*(h.f()-n.f())<a.f()&&(b=!b);h=d}return b}),google.a.Y.prototype.j||(google.a.Y.prototype.j=function(a){return google.a.ja?google.a.ja.Ya.Ka(this.N(),a)<=this.Ra():!0}),google.a.Ca.prototype.j=function(a){return this.F().contains(a)},google.a.Z.prototype.j=
function(a){return this.contains(a)});Array.prototype.indexOf||(Array.prototype.indexOf=function(a){if(null==this)throw new TypeError;var b=Object(this),c=b.length>>>0;if(0===c)return-1;var f=0;1<arguments.length&&(f=Number(arguments[1]),f!=f?f=0:0!=f&&Infinity!=f&&-Infinity!=f&&(f=(0<f||-1)*Math.floor(Math.abs(f))));if(f>=c)return-1;for(f=0<=f?f:Math.max(c-Math.abs(f),0);f<c;f++)if(f in b&&b[f]===a)return f;return-1});return p}
"object"===typeof exports?module.exports=E():"function"===typeof define&&define.Ia?define(["jquery","googlemaps!"],E):E();